### ISSUE TITLE
No audio with video downloads?

### ISSUE THREAD

**Issue by retalieight** [danguilherme/spotivy#43]
# Bug report

**What is the current behavior?**

I have no audio with the music videos that are downloaded. Is this normal? Is it supposed to only grab the video without audio?

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Download the music video with both video and audio.

**Other relevant information:**

- Spotivy version: 0.6.0
- Node.js version: v20.11.0
- Operating System: Windows 10

**Comment by retalieight** [comment]
I also received an error message during a download of a track:

```
[Downloading track] Get Scared - Sarcasm
                          Preparing download... C:\Users\chown\AppData\Roaming\npm\node_modules\spotivy\node_modules\miniget\dist\index.js:206
                let err = new Miniget.MinigetError(Status code: ${res.statusCode}, res.statusCode);
                          ^

MinigetError: Status code: 410
    at ClientRequest.<anonymous> (C:\Users\chown\AppData\Roaming\npm\node_modules\spotivy\node_modules\miniget\dist\index.js:206:27)
    at Object.onceWrapper (node:events:633:26)
    at ClientRequest.emit (node:events:518:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:535:22)
    at TLSSocket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on Stream instance at:
    at Stream.onerror (node:internal/streams/readable:1026:14)
    at Stream.emit (node:events:518:28)
    at Stream._send (C:\Users\chown\AppData\Roaming\npm\node_modules\spotivy\node_modules\highland\lib\index.js:998:18)
    at Stream.write (C:\Users\chown\AppData\Roaming\npm\node_modules\spotivy\node_modules\highland\lib\index.js:1658:18)
    at PassThrough.streamEndCb (C:\Users\chown\AppData\Roaming\npm\node_modules\spotivy\node_modules\highland\lib\index.js:494:20)
    at Object.onceWrapper (node:events:633:26)
    at PassThrough.emit (node:events:518:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 410
}
```

**Comment by danguilherme** [comment]
@retalieight could you please share the command you're running?

**Comment by retalieight** [comment]
@danguilherme ```spotivy playlist chownsauce myplaylistidhere -f video```. I read that ytdl-core doesn't merge the video and audio together like youtube-dl or yt-dlp would using ffmpeg. Is it not merging or am I missing something? Is it supposed to be a video without audio?

**Comment by danguilherme** [comment]
> Is it supposed to be a video without audio?

No, it's definitely supposed to be a video with audio. I'll check that out as soon as possible
